// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sshgggczyfamstybkppy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzaGdnZ2N6eWZhbXN0eWJrcHB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNDc0NDYsImV4cCI6MjA3MzgyMzQ0Nn0.ViNoAvzfztRcYe5gxhWLWQRsXu1twIto-WaFfe-wTJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});